# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "sinatra", "~> 4.1"
gem "rake", "~> 13.2"
gem "puma", "~> 6.6"
gem "rackup", "~> 2.2"
gem "require_all", "~> 3.0"
gem "sinatra-activerecord", "~> 2.0"
gem "rack-contrib", "~> 2.5"

gem "rerun", "~> 0.14.0", :group => :development
gem "pry", "~> 0.15.2", :group => :development

gem "rspec", "~> 3.13", :group => :test
gem "rack-test", "~> 2.2", :group => :test
